Successfully set up json server
adebisit/simple-task-mgmt-app pull request #2
Opened 2024-07-02 08:36 UTC by Haydox01

2024-07-02 21:32 UTC, adebisit commented
@Haydox01 can you provide some context and descriptions. 
For a task like this your description should contain the following

1. A short description about the task and the approach you took.
2. A snapshot or short demo video showing that it works
3. How we can test the new feature.

@preciousyaks17 and @Deolamma please follow this format in your PRs as well.

2024-07-02 21:37 UTC, adebisit requested changes

2024-07-02 21:37 UTC, adebisit commented on src/data/data.json
This seems like a great structure. 
But I want to recommend a simpler schema.

1. Exclude assignedTo: Implementing this means we probably have to consider functionalities for roles and permissions. Making the project a tad complicated.
2. Subtasks: Havae you considered how you might render that on the front end and if there'd be any complications involved?
3. I'd suggest priority be an integer instead of a string. like 1 - 5 (5 being the highest)
4. Finally rename "Tasks" to "tasks".

2024-07-02 21:59 UTC, tobi007 commented on src/data/data.json
I think the idea of a sub task is great it can be renders using like a tree/list component, nah person wey go implement go work sha

2024-07-02 22:01 UTC, tobi007 commented on src/data/data.json
> +      "status": "Pending",
Difference between status and completed?

2024-07-03 16:49 UTC, adebisit commented on src/data/data.json
The backend is a json server. @Haydox01 is there a way to implement Enums data types while working with Json servers.
If it isnt possible; maybe consider using Enums on the front end instead.

2024-07-04 14:12 UTC, adebisit commented on src/data/data.json
> +      "status": "Pending",
@Haydox01 RT.

2024-07-04 18:39 UTC, closed without merging